image: Ubuntu

stack: jdk 11

branches:
  only:
    - main

build: off

install:
  - chmod +x artifacts/app-mbank.jar
  - java -jar ./artifacts/app-mbank.jar &

build_script:
  - chmod +x gradlew
  - ./gradlew test --info
